logging:
  file:
    name: cx-flow.log

cx-flow:
  bug-tracker:  None
  bug-tracker-impl:
    - None
  filter-severity:
   # - High
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  codebash-url: https://checkmarx-demo.codebashing.com/courses/
  break-build: true
  enabled-vulnerability-scanners:
    - sast
    - sca

checkmarx:
  version: 9.0
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  base-url: ${CHECKMARX_SERVER}
  url: ${CHECKMARX_SERVER}/cxrestapi
  portal-url: ${CHECKMARX_SERVER}/cxwebinterface/Portal/CxWebService.asmx
  multi-tenant: true
  incremental: false
  scan-preset: Checkmarx Default
  configuration: Default Configuration
  scan-timeout: 120

sca:
  appUrl:  https://sca.scacheckmarx.com
  apiUrl:  https://api.scacheckmarx.com
  accessControlUrl:  https://platform.checkmarx.net
