version: 0.2 
 
phases: 
  install: 
    runtime-versions: 
      java: openjdk11 
  post_build: 
    commands: 
       - |
         java -jar /app/cx-flow.jar 
           --spring.profiles.active="sast" \
           --scan \
           --cx-team=$CHECKMARX_TEAM \
           --cx-project="Codebuild-Main" \
           --app="Codebuild" \
           --f=. \
           --checkmarx.base-url=$CHECKMARX_SERVER \
           --checkmarx.client-secret=$CHECKMARX_CLIENT_SECRET \
           --checkmarx.username=$CHECKMARX_USERNAME \
           --checkmarx.password=$CHECKMARX_PASSWORD \
           --checkmarx.client-id=$CHECKMARX_CLIENT_ID \
           --checkmarx.preset=$CHECKMARX_PRESET \
           --checkmarx.scope=$CHECKMARX_SCOPE \
           --checkmarx.configuration=$CHECKMARX_CONFIGURATION
       # --cx-flow.bug-tracker=$CX_FLOW_BUG_TRACKER \
       # --cx-flow.bug-tracker-impl=$CX_FLOW_BUG_TRACKER \
       # --cx-flow.filter-severity=$CHECKMARX_FILTER_SEVERITIES \
       # --cx-flow.filter-state=$CHECKMARX_FILTER_STATE \
       # --checkmarx.exclude-folders=$CHECKMARX_EXCLUDE_FOLDERS \
       # --checkmarx.exclude-files=$CHECKMARX_EXCLUDE_FILES
