version: 0.2 
 
phases: 
  install: 
    runtime-versions: 
      java: openjdk11 
 # prebuild:
  #  commands:
  #    docker pull checkmarx/cx-flow
 # build:
  #   commands:
  #    docker run checkmarx/cx-flow
  post_build: 
    commands: 
       - java -jar /app/cx-flow.jar \
         --scan \
         -f=$(CODEBUILD_SRC_DIR) \
         --cx-project="CodeBuild Test" \
         --namespace="CodeBuild Test" \
         --app="CodeBuild Test"
