version: 0.2 

env:
  variables:
    CHECKMARX_BUGTRACKER: "None"
    #GH_BRANCH: "$CODEBUILD_WEBHOOK_HEAD_REF" # refs/heads/<branch_name>
    #GH_REPO_NAME: "cxflow_demo"
    #GH_REPO_OWNER: "cxflow_demo" # Codertocat
    #ADD_PARAMS: "--namespace=$GH_REPO_OWNER --repo-name=$GH_REPO_NAME --branch=$GH_BRANCH"
    #ADD_PARAMS: "--config=cx.config --checkmarx.settings-override=true --jira.url=$JIRA_URL --jira.username=$JIRA_USER --jira.token=$JIRA_TOKEN"
phases: 
  pre_build: 
    commands: 
       - export CX_PROJECT_NAME=$(basename "$CODEBUILD_SOURCE_REPO_URL") 
       - export CX_PROJECT_BRANCH=$(basename "$CODEBUILD_SOURCE_VERSION") 
       - env
       - |
         java -jar /app/cx-flow.jar \
           --scan \
           --cx-project="Codebuild-main" \
           --app="cxflow_demo" \
           --branch="main" \
           --repo-name="cxflow_demo" \
           --namespace="cxflow_demo" \
           --f=. \
           --cx-flow.enabled-vulnerability-scanners="$CHECKMARX_SCANNERS"  \
           --checkmarx.version="9.0" \
           --checkmarx.base-url="$CHECKMARX_SERVER" \
           --checkmarx.client-secret="$CHECKMARX_CLIENT_SECRET" \
           --checkmarx.username="$CHECKMARX_USERNAME" \
           --checkmarx.password="$CHECKMARX_PASSWORD" \
           --checkmarx.client-id="$CHECKMARX_CLIENT_ID" \
           --cx-team="$CHECKMARX_TEAM" \
           --checkmarx.preset="$CHECKMARX_PRESET" \
           --checkmarx.scope="$CHECKMARX_SCOPE" \
           --checkmarx.configuration="$CHECKMARX_CONFIGURATION" \
           --cx-flow.bug-tracker="$CHECKMARX_BUGTRACKER" \
           --cx-flow.bug-tracker-impl="$CHECKMARX_BUGTRACKER" \
           --cx-flow.filter-severity="$CHECKMARX_FILTER_SEVERITIES" \
           --cx-flow.filter-state="$CHECKMARX_FILTER_STATE" \
           --checkmarx.exclude-folders="$CHECKMARX_EXCLUDE_FOLDERS" \
           --checkmarx.exclude-files="$CHECKMARX_EXCLUDE_FILES" \
           "$ADD_PARAMS"

