version: 0.2 
 
phases: 
  post_build: 
    commands: 
       - |
         java -jar /app/cx-flow.jar \
           --scan \
           --cx-project="Codebuild-main" \
           --app="Codebuild-main" \
           --branch="main" \
           --repo-name="Codebuild" \
           --namespace="AWS" \
           --f=. \
           --cx-flow.enabled-vulnerability-scanners="sast"  \
           --checkmarx.version="9.0" \
           --checkmarx.base-url=$CHECKMARX_SERVER \
           --checkmarx.client-secret=$CHECKMARX_CLIENT_SECRET \
           --checkmarx.username=$CHECKMARX_USERNAME \
           --checkmarx.password=$CHECKMARX_PASSWORD \
           --checkmarx.client-id=$CHECKMARX_CLIENT_ID \
           --cx-team=$CHECKMARX_TEAM \
           --checkmarx.preset="Checkmarx Default" \
           --checkmarx.scope="$(CHECKMARX_SCOPE)" \
           --checkmarx.configuration=$CHECKMARX_CONFIGURATION \
           --cx-flow.bug-tracker="None" \
           --cx-flow.bug-tracker-impl="None" 
       # --cx-flow.filter-severity=$CHECKMARX_FILTER_SEVERITIES \
       # --cx-flow.filter-state=$CHECKMARX_FILTER_STATE \
       # --checkmarx.exclude-folders=$CHECKMARX_EXCLUDE_FOLDERS \
       # --checkmarx.exclude-files=$CHECKMARX_EXCLUDE_FILES

