# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: docker://docker.io/checkmarxts/cxflow

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: |
        echo Hello, world!
        
        echo "logging: \nfile: \nname: cx-flow.log \ncx-flow: \nbug-tracker:  JIRA\n bug-tracker-impl: - GitHub filter-severity: - High mitre-url: https://cwe.mitre.org/data/definitions/%s.html break-build: true checkmarx: version: 9.0 username: ${CHECKMARX_USERNAME} password: ${CHECKMARX_PASSWORD} client-secret: 014DF517-39D1-4453-B7B3-9930C563627C base-url: ${CHECKMARX_SERVER} url: ${CHECKMARX_SERVER}/cxrestapi portal-url: ${CHECKMARX_SERVER}/cxwebinterface/Portal/CxWebService.asmx multi-tenant: true incremental: true scan-preset: Checkmarx Default configuration: Default Configuration team: ${CHECKMARX_TEAM} scan-timeout: 120 jira: url: https://jbrotsos.atlassian.net/ username: james.brotsos@checkmarx.com token: twEOVJXm91bmE3EXBCw158B0 project: CXFLOW issue-type: Bug priorities: High: High Medium: Medium Low: Low Informational: Lowest open-transition: In Progress close-transition: Done open-status: - Backlog - Selected for Development - In Progress closed-status: - Done" >> application.yml
        cat application.yml
        java -jar /app/cx-flow.jar --spring.config.location=./application.yml --scan --cx-team="/CxServer/jbrotsos" --cx-project="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" --app="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" --cx-flow.break-build=false --f=. 


    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
